services:
  tomee:
    image: openjdk:17
    container_name: java-change
    ports:
      - "127.0.0.1:8080:8080"
      # - "127.0.0.1:8006:8005"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./target/apache-tomee:/usr/local/tomee
    working_dir: /usr/local/tomee
    command: ["bin/catalina.sh", "run"]
    environment:
      - JAVA_OPTS=-Xmx512m
    restart: unless-stopped
