tomee.remote.support=true
openejb.cdi.activated=true
openejb.system.apps=true
tomee.serialization.class.blacklist=-

tomee.serialization.debug=true
log4j.logger.org.apache.openejb.core.rmi=DEBUG

openejb.remote.jndi.operations=all
